# Development configuration
server:
  host: "localhost"
  port: 8080
  read_timeout: 30
  write_timeout: 30
  idle_timeout: 120
  shutdown_timeout: 30
  prefork: false

data:
  reviews_path: "data/siteReviews.json"
  predictions_path: "data/reviews.json"

logger:
  level: "debug"
  format: "console"
  output_path: ""

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "reviews_db_dev"
  user: "postgres"
  password: "dev_password"
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: 5