version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
      - ./logs:/root/logs
      - ./config.prod.yaml:/root/config.yaml
    environment:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - LOG_OUTPUT_PATH=logs/app.log
    restart: unless-stopped

networks:
  reviews-network:
    driver: bridge